# Web service configuration
server:
  port: 9100

logging:
  level:
    org.springframework.web: DEBUG

# Node configuration
app:
  wsInit: http://localhost:9101/init
  wsCmd:  http://localhost:9101/cmd